### ISSUE TITLE
Update Teams Card Endpoint

### ISSUE THREAD

**Issue by akroon3r** [SierraSystems/ntt-data-notification-service#70]
**Estimate** 1d

- HTTP POST request to our service with card specific information in order to change a status (ie// acknowledged, taken etc.)

- Service redirects back to Teams to update card with supplied information

**Comment by adodge-bcg** [comment]
Considered adding the username of person updating status to a card but MessageCards have no access to that context https://poszytek.eu/en/microsoft-en/microsoft-message-cards-the-ultimate-guide/
